version: '3.5'

services:
  my_app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: /bin/sh -c "gunicorn --workers=3 backend.be_rich.wsgi -b 0.0.0.0:8080"
    restart: always
    volumes:
      - ..:/srv/app
      - app-www:/srv/www
    expose:
      - "8080"

    environment:
      DJANGO_DATABASE: "pgsql://richman:pass@postgres/berich"
      DJANGO_STATIC_ROOT: "/srv/www/static"
      SECRET_KEY: "+bm^3jl=+siiv6ybqbf330igkh+z-(__1%vj+^o^iwuf-(*ot4"
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: "/srv/app"
      PYTHONDONTWRITEBYTECODE: "1"
      DJANGO_SETTINGS_MODULE: "backend.be_rich.settings"

    depends_on:
      - postgres
      - nginx

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../logs:/srv/app/logs
      - app-www:/srv/www
    ports:
      - "1221:80"

  postgres:
    build:
      context: ../
      dockerfile: docker/db/Dockerfile
    restart: always
    expose:
      - "5432"
    environment:
      - "DB_USER=richman"
      - "DB_PASSWORD=pass"
      - "DB_DATABASE=berich"
      - "POSTGRES_PASSWORD=password"
    networks:
      default:
        aliases:
          - 'postgres'

networks:
  default:

volumes:
  app-www:
